---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by TerrorBlade.
--- DateTime: 2021/1/29 22:34
---
print('hello')
GaitParams = {}
GaitParams["stance_height"] = 0.18
print(GaitParams.stance_height)




